version: "3.2"
services:
  nginx:
      build: ./Nginx
      links:
          - node1:node1
          - node2:node2
          - node3:node3
      ports:
          - "80:80"
  node1:
      build: ./Node
#      links:
      ports:
          - "8080"
  node2:
      build: ./Node
#      links:
      ports:
          - "8080"
  node3:
      build: ./Node
#      links:
      ports:
          - "8080"
